set vpn ipsec authentication psk PSK-VPN-SITE-B id '91.205.114.2'
set vpn ipsec authentication psk PSK-VPN-SITE-B secret 'ROC-SITE-B'
set vpn ipsec authentication psk PSK-VPN-SITE-C id '176.58.32.2'
set vpn ipsec authentication psk PSK-VPN-SITE-C secret 'ROC-SITE-C'
set vpn ipsec esp-group ESP lifetime '3600'
set vpn ipsec esp-group ESP mode 'tunnel'
set vpn ipsec esp-group ESP pfs 'enable'
set vpn ipsec esp-group ESP proposal 10 encryption 'aes256'
set vpn ipsec esp-group ESP proposal 10 hash 'sha256'
set vpn ipsec ike-group IKE close-action 'start'
set vpn ipsec ike-group IKE key-exchange 'ikev2'
set vpn ipsec ike-group IKE lifetime '86400'
set vpn ipsec ike-group IKE proposal 10 dh-group '31'
set vpn ipsec ike-group IKE proposal 10 encryption 'aes256'
set vpn ipsec ike-group IKE proposal 10 hash 'sha256'
set vpn ipsec ike-group IKE proposal 10 prf 'prfsha256'
set vpn ipsec interface 'eth0'
set vpn ipsec options disable-route-autoinstall
set vpn ipsec site-to-site peer SITE-B authentication local-id '185.142.12.2'
set vpn ipsec site-to-site peer SITE-B authentication mode 'pre-shared-secret'
set vpn ipsec site-to-site peer SITE-B authentication remote-id '91.205.114.2'
set vpn ipsec site-to-site peer SITE-B connection-type 'initiate'
set vpn ipsec site-to-site peer SITE-B default-esp-group 'ESP'
set vpn ipsec site-to-site peer SITE-B ike-group 'IKE'
set vpn ipsec site-to-site peer SITE-B local-address '185.142.12.2'
set vpn ipsec site-to-site peer SITE-B remote-address '91.205.114.2'
set vpn ipsec site-to-site peer SITE-B tunnel 1 local prefix '0.0.0.0/0'
set vpn ipsec site-to-site peer SITE-B tunnel 1 remote prefix '0.0.0.0/0'
set vpn ipsec site-to-site peer SITE-B vti bind 'vti0'
set vpn ipsec site-to-site peer SITE-C authentication local-id '185.142.12.2'
set vpn ipsec site-to-site peer SITE-C authentication mode 'pre-shared-secret'
set vpn ipsec site-to-site peer SITE-C authentication remote-id '176.58.32.2'
set vpn ipsec site-to-site peer SITE-C connection-type 'initiate'
set vpn ipsec site-to-site peer SITE-C default-esp-group 'ESP'
set vpn ipsec site-to-site peer SITE-C ike-group 'IKE'
set vpn ipsec site-to-site peer SITE-C local-address '185.142.12.2'
set vpn ipsec site-to-site peer SITE-C remote-address '176.58.32.2'
set vpn ipsec site-to-site peer SITE-C tunnel 1 local prefix '0.0.0.0/0'
set vpn ipsec site-to-site peer SITE-C tunnel 1 remote prefix '0.0.0.0/0'
set vpn ipsec site-to-site peer SITE-C vti bind 'vti1'
