set vpn ipsec authentication psk PSK-CA id '185.142.12.2'
set vpn ipsec authentication psk PSK-CA secret 'PSK-AC-2026'
set vpn ipsec authentication psk PSK-CB id '91.205.114.2'
set vpn ipsec authentication psk PSK-CB secret 'PSK-BC-2026'
set vpn ipsec esp-group ESP lifetime '3600'
set vpn ipsec esp-group ESP mode 'tunnel'
set vpn ipsec esp-group ESP pfs 'enable'
set vpn ipsec esp-group ESP proposal 10 encryption 'aes256'
set vpn ipsec esp-group ESP proposal 10 hash 'sha256'
set vpn ipsec ike-group IKE close-action 'start'
set vpn ipsec ike-group IKE key-exchange 'ikev2'
set vpn ipsec ike-group IKE lifetime '86400'
set vpn ipsec ike-group IKE proposal 10 dh-group '31'
set vpn ipsec ike-group IKE proposal 10 encryption 'aes256'
set vpn ipsec ike-group IKE proposal 10 hash 'sha256'
set vpn ipsec ike-group IKE proposal 10 prf 'prfsha256'
set vpn ipsec interface 'eth0'
set vpn ipsec options disable-route-autoinstall
set vpn ipsec site-to-site peer SITE-A authentication local-id '176.58.32.2'
set vpn ipsec site-to-site peer SITE-A authentication mode 'pre-shared-secret'
set vpn ipsec site-to-site peer SITE-A authentication remote-id '185.142.12.2'
set vpn ipsec site-to-site peer SITE-A connection-type 'initiate'
set vpn ipsec site-to-site peer SITE-A default-esp-group 'ESP'
set vpn ipsec site-to-site peer SITE-A ike-group 'IKE'
set vpn ipsec site-to-site peer SITE-A local-address '176.58.32.2'
set vpn ipsec site-to-site peer SITE-A remote-address '185.142.12.2'
set vpn ipsec site-to-site peer SITE-A vti bind 'vti0'