set interfaces ethernet eth0 address '185.142.12.2/30'
set interfaces ethernet eth0 description 'Richting het internet'
set interfaces ethernet eth0 hw-id '00:0c:29:35:d9:85'
set interfaces ethernet eth1 address '10.0.10.1/24'
set interfaces ethernet eth1 description 'LAN Beheer'
set interfaces ethernet eth1 hw-id '00:0c:29:35:d9:8f'
set interfaces ethernet eth2 address '10.0.20.1/24'
set interfaces ethernet eth2 description 'LAN Leerlingen'
set interfaces ethernet eth2 hw-id '00:0c:29:35:d9:99'
set interfaces ethernet eth3 address '10.0.23.1/24'
set interfaces ethernet eth3 description 'LAN Docenten'
set interfaces ethernet eth3 hw-id '00:0c:29:35:d9:a3'
set interfaces ethernet eth4 address '10.0.100.1/24'
set interfaces ethernet eth4 description 'LAN Servers'
set interfaces ethernet eth4 hw-id '00:0c:29:35:d9:ad'
set interfaces ethernet eth5 address 'dhcp'
set interfaces ethernet eth5 description 'Bridged verbinding voor SSH gebruiksgemak'
set interfaces ethernet eth5 hw-id '00:0c:29:35:d9:b7'
set interfaces loopback lo
set interfaces vti vti0 address '172.16.100.1/30'
set interfaces vti vti0 description 'Link naar Site-B'
set interfaces vti vti1 address '172.16.100.5/30'
set interfaces vti vti1 description 'Link naar Site-C'
set nat source rule 10 description 'NAT omzeilen voor VPN verkeer tussen sites'
set nat source rule 10 destination address '10.0.0.0/16'
set nat source rule 10 exclude
set nat source rule 10 outbound-interface name 'eth0'
set nat source rule 10 source address '10.0.0.0/16'
set nat source rule 20 description 'NAT Overload voor internettoegang vanaf LAN'
set nat source rule 20 outbound-interface name 'eth0'
set nat source rule 20 source address '10.0.0.0/16'
set nat source rule 20 translation address 'masquerade'
set protocols ospf area 0 network '10.0.10.0/24'
set protocols ospf area 0 network '10.0.20.0/24'
set protocols ospf area 0 network '10.0.23.0/24'
set protocols ospf area 0 network '10.0.100.0/24'
set service ntp allow-client address '127.0.0.0/8'
set service ntp allow-client address '169.254.0.0/16'
set service ntp allow-client address '10.0.0.0/8'
set service ntp allow-client address '172.16.0.0/12'
set service ntp allow-client address '192.168.0.0/16'
set service ntp allow-client address '::1/128'
set service ntp allow-client address 'fe80::/10'
set service ntp allow-client address 'fc00::/7'
set service ntp server time1.vyos.net
set service ntp server time2.vyos.net
set service ntp server time3.vyos.net
set service ssh port '22'
set system config-management commit-revisions '100'
set system console device ttyS0 kernel
set system console device ttyS0 speed '115200'
set system host-name 'Site-A'
set system login banner post-login 'Je bent momenteel ingelogd op Router: Site-A - hoofdcampus'
set system login banner pre-login 'ROC SILENTSENT1NEL - ROUTER SITE-A (HOOFDCAMPUS) - WAARSCHUWING: Ongeautoriseerde toegang is verboden.'
set system login operator-group default command-policy allow '*'
set system login user vyos authentication encrypted-password '$6$rounds=656000$Vy/.ru1x3dnknJzL$EhuClSisVJRtI3Fte7zgRKwcTcKEC9Y1HF/.POX2VHtFFZXR17WAH1jwW49RXfs3vVlshHiWxGV4TEhsDBjwA/'
set system login user vyos authentication plaintext-password ''
set system option reboot-on-upgrade-failure '5'
set system syslog local facility all level 'info'
set system syslog local facility local7 level 'debug'