set interfaces ethernet eth0 address '91.205.114.2/30'
set interfaces ethernet eth0 description 'Richting het internet'
set interfaces ethernet eth0 hw-id '00:0c:29:76:90:67'
set interfaces ethernet eth0 offload gro
set interfaces ethernet eth0 offload gso
set interfaces ethernet eth0 offload sg
set interfaces ethernet eth0 offload tso
set interfaces ethernet eth1 address '10.0.11.1/24'
set interfaces ethernet eth1 description 'LAN Beheer'
set interfaces ethernet eth1 hw-id '00:0c:29:76:90:71'
set interfaces ethernet eth1 offload gro
set interfaces ethernet eth1 offload gso
set interfaces ethernet eth1 offload sg
set interfaces ethernet eth1 offload tso
set interfaces ethernet eth2 address '10.0.21.1/24'
set interfaces ethernet eth2 description 'LAN Leerlingen'
set interfaces ethernet eth3 address '10.0.24.1/24'
set interfaces ethernet eth3 description 'LAN Docenten'
set interfaces ethernet eth4 address 'dhcp'
set interfaces ethernet eth4 description 'Bridged verbinding voor SSH gebruiksgemak'
set interfaces loopback lo
set service ntp allow-client address '127.0.0.0/8'
set service ntp allow-client address '169.254.0.0/16'
set service ntp allow-client address '10.0.0.0/8'
set service ntp allow-client address '172.16.0.0/12'
set service ntp allow-client address '192.168.0.0/16'
set service ntp allow-client address '::1/128'
set service ntp allow-client address 'fe80::/10'
set service ntp allow-client address 'fc00::/7'
set service ntp server time1.vyos.net
set service ntp server time2.vyos.net
set service ntp server time3.vyos.net
set service ssh
set system config-management commit-revisions '100'
set system console device ttyS0 kernel
set system console device ttyS0 speed '115200'
set system host-name 'Site-B'
set system login banner post-login 'Je bent momenteel ingelogd op Router: Site-B - campus B'
set system login banner pre-login 'ROC SILENTSENT1NEL - ROUTER SITE-B (CAMPUS B) - WAARSCHUWING: Ongeautoriseerde toegang is verboden.'
set system login operator-group default command-policy allow '*'
set system login user vyos authentication encrypted-password '$6$rounds=656000$OCa3looJH.8AipV2$yHhcxt4LLNuMKep4.ZyY5m5rEVCWr8AyEeRb3MR3yzXdkMiqGssu1cPslbDMHw56SXPTxTcxfCdU14hOKsedx0'
set system login user vyos authentication plaintext-password ''
set system option reboot-on-upgrade-failure '5'
set system syslog local facility all level 'info'
set system syslog local facility local7 level 'debug'