# Config informatie ROC-DHCP-Site_C:

## Hostname: srv-c-dhcp-03
## Wachtwoord: R0C_DHCPc_@dm1n!
## Full name: DHCP Beheerder Site-C
## Username: dhcp-beheerder-site_c
## IP-adres: 10.0.112.30



{
  // This is a basic configuration for the Kea DHCPv4 server. Subnet declarations
  // are mostly commented out and no interfaces are listed. Therefore, the servers
  // will not listen or respond to any queries.
  //
  // Make sure you at least:
  // - change the network interface names
  // - change the subnets to match your actual network
  // - change the option values to match your network
  //
  // This configuration contains only DHCPv4 settings.


  "Dhcp4": {
    "interfaces-config": {
      "interfaces": [ "ens34" ]
    },


    "valid-lifetime": 3600,
    "renew-timer": 900,
    "rebind-timer": 1800,

    "option-data": [
      {
        "name": "domain-name-servers",
        "data": "10.0.100.31"
      },
      {
        "name": "domain-name",
        "data": "roc-silentsentinel.internal"
      }
    ],


    "subnet4": [
      {
        "id": 12,
        "subnet": "10.0.12.0/24",
        "pools": [ { "pool": "10.0.12.100 - 10.0.12.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.12.1" } ]
      },

      {
        "id": 22,
        "subnet": "10.0.22.0/24",
        "pools": [ { "pool": "10.0.22.100 - 10.0.22.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.22.1" } ]
      },

      {
        "id": 25,
        "subnet": "10.0.25.0/24",
        "pools": [ { "pool": "10.0.25.100 - 10.0.25.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.25.1" } ]
      }
    ]
  }
}