# Config informatie ROC-WEB:

## Hostname: ROC-DNS
## Domain name: roc-silentsentinel.internal
## Wachtwoord: R0C_WEB_@dm1n!
## Full name: Webserver Beheerder
## Username: web-beheerder
## IP-adres: 10.0.100.32

/etc/nginx/sites-available & /etc/nginx/sites-enabled:

server {
        listen 80;
        server_name roc-silentsentinel.internal www.roc-silentsentinel.internal;

        root /var/www/roc-silentsentinel.internal/html;
        index index.html;

        location / {
                try_files $uri $uri/ =404;
        }
}