# Config informatie ROC-DHCP:

## Hostname: srv-a-dhcp-01
## Wachtwoord: R0C_DHCP_@dm1n!
## Full name: DHCP Beheerder
## Username: dhcp-beheerder
## IP-adres: 10.0.100.30




{
  // This is a basic configuration for the Kea DHCPv4 server. Subnet declarations
  // are mostly commented out and no interfaces are listed. Therefore, the servers
  // will not listen or respond to any queries.
  //
  // Make sure you at least:
  // - change the network interface names
  // - change the subnets to match your actual network
  // - change the option values to match your network
  //
  // This configuration contains only DHCPv4 settings.


  "Dhcp4": {
    "interfaces-config": {
      "interfaces": [ "*" ]
    },

    "subnet4": [
      {
        "id": 10,
        "subnet": "10.0.10.0/24",
        "pools": [ { "pool": "10.0.10.100 - 10.0.10.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.10.1" } ]
      },

      {
        "id": 20,
        "subnet": "10.0.20.0/24",
        "pools": [ { "pool": "10.0.20.100 - 10.0.20.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.20.1" } ]
      },

      {
        "id": 23,
        "subnet": "10.0.23.0/24",
        "pools": [ { "pool": "10.0.23.100 - 10.0.23.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.23.1" } ]
      },

      {
        "id": 11,
        "subnet": "10.0.11.0/24",
        "pools": [ { "pool": "10.0.11.100 - 10.0.11.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.11.1" } ]
      },

      {
        "id": 21,
        "subnet": "10.0.21.0/24",
        "pools": [ { "pool": "10.0.21.100 - 10.0.21.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.21.1" } ]
      },

      {
        "id": 24,
        "subnet": "10.0.24.0/24",
        "pools": [ { "pool": "10.0.24.100 - 10.0.24.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.24.1" } ]
      },

      {
        "id": 12,
        "subnet": "10.0.12.0/24",
        "pools": [ { "pool": "10.0.12.100 - 10.0.12.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.12.1" } ]
      },

      {
        "id": 22,
        "subnet": "10.0.22.0/24",
        "pools": [ { "pool": "10.0.22.100 - 10.0.22.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.22.1" } ]
      },

      {
        "id": 25,
        "subnet": "10.0.25.0/24",
        "pools": [ { "pool": "10.0.25.100 - 10.0.25.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.25.1" } ]
      }
    ]
  }
}