# Config informatie ROC-DNS:

## Hostname: ROC-DNS
## Domain name: 
## Wachtwoord: R0C_DNS_@dm1n!
## Full name: DNS Beheerder
## Username: dns-beheerder
## IP-adres: 10.0.100.31

# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

       # unbound.conf(5) config file for unbound(8).
 server:
   directory: "/etc/unbound"
   username: unbound
   # make sure unbound can access entropy from inside the chroot.
   # e.g. on linux the use these commands (on BSD, devfs(8) is used):
   #      mount --bind -n /dev/urandom /etc/unbound/dev/urandom
   # and  mount --bind -n /dev/log /etc/unbound/dev/log
   chroot: "/etc/unbound"
   # logfile: "/etc/unbound/unbound.log"  #uncomment to use logfile.
   pidfile: "/etc/unbound/unbound.pid"
   # verbosity: 1      # uncomment and increase to get more logging.
   # listen on all interfaces, answer queries from the local subnet.
   interface: 0.0.0.0
#  interface: ::0

# Access control Site-A
   access-control: 10.0.10.0/24 allow
   access-control: 10.0.11.0/24 allow
   access-control: 10.0.12.0/24 allow
   access-control: 10.0.100.0/24 allow

# Access control Site-B
   access-control: 10.0.20.0/24 allow
   access-control: 10.0.21.0/24 allow
   access-control: 10.0.22.0/24 allow

# Access control Site-C
   access-control: 10.0.23.0/24 allow
   access-control: 10.0.24.0/24 allow
   access-control: 10.0.25.0/24 allow
#  access-control: 2001:DB8::/64 allow


# Prestaties & security

   cache-max-ttl: 86400
   cache-min-ttl: 300
   prefetch: yes
   qname-minimisation: yes

# Local DNS Zone (ROC SilentSentinel)
   local-zone: "roc-silentsentinel.internal." static

# Interne services

# DNS Server (Site-A)

   local-data: "dns.roc-silentsentinel.internal. A 10.0.100.31"

# Web server
   local-data: "www.roc-silentsentinel.internal. A 10.0.100.32"
   local-data: "portal.roc-silentsentinel.internal. A 10.0.100.32"

# Optionele alias(s)
    local-data: "web.roc-silentsentinel.internal. A 10.0.100.32"