# Config informatie ROC-DHCP-Site_B:

## Hostname: srv-b-dhcp-02
## Wachtwoord: R0C_DHCPb_@dm1n!
## Full name: DHCP Beheerder Site-B
## Username: dhcp-beheerder-site_b
## IP-adres: 10.0.111.30



{
  // This is a basic configuration for the Kea DHCPv4 server. Subnet declarations
  // are mostly commented out and no interfaces are listed. Therefore, the servers
  // will not listen or respond to any queries.
  //
  // Make sure you at least:
  // - change the network interface names
  // - change the subnets to match your actual network
  // - change the option values to match your network
  //
  // This configuration contains only DHCPv4 settings.


  "Dhcp4": {
    "interfaces-config": {
      "interfaces": [ "*" ]
    },

    "subnet4": [
      {
        "id": 11,
        "subnet": "10.0.11.0/24",
        "pools": [ { "pool": "10.0.11.100 - 10.0.11.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.11.1" } ]
      },

      {
        "id": 21,
        "subnet": "10.0.21.0/24",
        "pools": [ { "pool": "10.0.21.100 - 10.0.21.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.21.1" } ]
      },

      {
        "id": 24,
        "subnet": "10.0.24.0/24",
        "pools": [ { "pool": "10.0.24.100 - 10.0.24.200" } ],
        "option-data": [ { "name": "routers", "data": "10.0.24.1" } ]
      }
    ]
  }
}